### ISSUE TITLE
Mobile Chrome Bug

### ISSUE THREAD

**Issue by ybentov** [ScoopThemes/Oleose#2]
When opening the template in chrome for mobile (Android) and trying to scroll down, it doesn't move.
You have to open the menu, click on the first tab and only then you can start scrolling.
Can this be fixed please?
Thanks.

**Comment by mshaaban0** [comment]
Fixed, Thanks

**Comment by ChiaraPi** [comment]
Hi, sorry for bother you. I've built my landing page with the old release of Oleose, Berry version...What files I have to change and not lose all my changes in index and various css files?
Thank you
